export const SAVE_MY_PROFILE = "SAVE_MY_PROFILE";
export const LOGOUT_MY_PROFILE = "LOGOUT_MY_PROFILE";
export const SHOW_RESERVATION = "SHOW_RESERVATION";
export const SHOW_CREATE_RESERVATION = "SHOW_CREATE_RESERVATION";
export const SHOW_CARD_EVENT = "SHOW_CARD_EVENT";
